XyTech/Controllers/ProfitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XyTech.Models;
using System.Globalization;
using XyTech.Attributes;

namespace XyTech.Controllers
{
    [CustomAuthorize]
    public class ProfitController : Controller
    {
        private db_XyTechEntities db = new db_XyTechEntities();

        // GET: Profit
        public ActionResult Index()
        {
            ViewBag.countlandlord = db.tb_landlord.Count(l => l.l_due <= DateTime.Today && l.l_active == "1");

            if (TempData.ContainsKey("success"))
            {
                ViewBag.Message = TempData["success"].ToString();
            }

            int currentDay = DateTime.Today.Day;
            var tenants = db.tb_tenant.ToList();

            if (currentDay < 7 && tenants.Any(t => t.t_indate.Day > 23))
            {
                currentDay += 30;
            }
            ViewBag.counttenant = tenants.Count(t => t.t_indate.Day >= (currentDay - 7) && t.t_indate.Month != DateTime.Today.Month && t.t_indate.Day < currentDay && (t.t_paymentstatus == 2 || t.t_paymentstatus == 3));

            if (Session["usertype"] != null && Session["usertype"].Equals("Investor"))
            {
                var userId = Convert.ToInt32(Session["id"]);
                var tb_investor = db.tb_investor.FirstOrDefault(i => i.i_user == userId);

                if (tb_investor != null)
                {
                    int i_id = tb_investor.i_id;
                    var currentMonth = DateTime.Now.Month;
                    var currentYear = DateTime.Now.Year;
                    var month = $"{currentYear}-{currentMonth}";

                    var tb_profit = db.tb_profit
                        .Where(p => p.p_investor == i_id && !p.p_month.Equals(month))
                        .ToList();

                    if (tb_profit != null)
                    {
                        foreach (var profitEntry in tb_profit)
                        {
                            // Retrieve investor name from tb_user
                            var investor = db.tb_user.FirstOrDefault(u => u.u_id == tb_investor.i_user);
                            if (investor != null)
                                profitEntry.InvestorUsername = investor.u_username;
                        }

                        tb_profit = tb_profit
                            .OrderByDescending(p => Convert.ToInt32(p.p_month.Split('-')[0])) // Order by year
                            .ThenByDescending(p => Convert.ToInt32(p.p_month.Split('-')[1])) // Order by month
                            .ToList();

                        return View(tb_profit);
                    }
                    else
                    {
                        return View();
                    }
                }
            }

            var profit = db.tb_profit
                .Include(t => t.tb_investor)
                .ToList()
                .Select(p => new tb_profit
                {
                    p_id = p.p_id,
                    p_investor = p.p_investor,
                    p_month = p.p_month,
                    p_profit = p.p_profit,
                    p_lot = p.tb_investor.i_lot,
                    InvestorUsername = db.tb_user.FirstOrDefault(u => u.u_id == p.tb_investor.i_user)?.u_username
                })
                .OrderByDescending(p => Convert.ToInt32(p.p_month.Split('-')[0])) // Order by year
                .ThenByDescending(p => Convert.ToInt32(p.p_month.Split('-')[1])) // Order by month
                .ToList();


            return View(profit);
            
        }


        // GET: Profit/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_profit tb_profit = db.tb_profit.Find(id);
            if (tb_profit == null)
            {
                return HttpNotFound();
            }
            return View(tb_profit);
        }

        // GET: Profit/Create
        public ActionResult Create()
        {
            ViewBag.p_investor = new SelectList(db.tb_investor, "i_id", "i_active");
            return View();
        }

        // POST: Profit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "p_id,p_investor,p_month,p_profit")] tb_profit tb_profit)
        {
            if (ModelState.IsValid)
            {
                db.tb_profit.Add(tb_profit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.p_investor = new SelectList(db.tb_investor, "i_id", "i_active", tb_profit.p_investor);
            return View(tb_profit);
        }

        // GET: Profit/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_profit tb_profit = db.tb_profit.Find(id);

            if (tb_profit == null)
            {
                return HttpNotFound();
            }
            int investorId = tb_profit.p_investor;
            tb_investor investor = db.tb_investor.Find(investorId);
            if (investor != null)
            {
                int userId = investor.i_user;
                tb_user user = db.tb_user.Find(userId);
                if (user != null)
                {
                    ViewBag.u_username = user.u_username;
                }
                else
                {
                    ViewBag.u_username = "N/A"; // Provide a default value if user is not found
                }
            }
            else
            {
                ViewBag.u_username = "N/A"; // Provide a default value if investor is not found
            }

            return View(tb_profit);
        }

        // POST: Profit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "p_id,p_investor,p_month,p_profit")] tb_profit tb_profit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_profit).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Profit is successfully edited!";
                return RedirectToAction("Index");
            }
            tb_investor investor = db.tb_investor.Find(tb_profit.p_investor);
            if (investor != null)
            {
                int userId = investor.i_user;
                tb_user user = db.tb_user.Find(userId);
                if (user != null)
                {
                    ViewBag.u_username = user.u_username;
                }
                else
                {
                    ViewBag.u_username = "N/A"; // Provide a default value if user is not found
                }
            }
            else
            {
                ViewBag.u_username = "N/A"; // Provide a default value if investor is not found
            }
            return View(tb_profit);
        }

        // GET: Profit/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_profit tb_profit = db.tb_profit.Find(id);
            if (tb_profit == null)
            {
                return HttpNotFound();
            }
            return View(tb_profit);
        }

        // POST: Profit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_profit tb_profit = db.tb_profit.Find(id);
            db.tb_profit.Remove(tb_profit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

XyTech/Views/Profit/Create.cshtml
@model XyTech.Models.tb_profit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tb_profit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.p_investor, "p_investor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("p_investor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.p_investor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.p_month, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.p_month, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.p_month, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.p_profit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.p_profit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.p_profit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

XyTech/Views/Profit/Delete.cshtml
@model XyTech.Models.tb_profit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tb_profit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.p_month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.p_month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.p_profit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.p_profit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_investor.i_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_investor.i_active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

XyTech/Views/Profit/Details.cshtml
@model XyTech.Models.tb_profit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tb_profit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.p_month)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.p_month)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.p_profit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.p_profit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tb_investor.i_active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tb_investor.i_active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.p_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

XyTech/Views/Profit/Edit.cshtml
@model XyTech.Models.tb_profit

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Profit", new { id = Model.p_id }, FormMethod.Post, new { id = "deleteForm" }))
{
    @Html.AntiForgeryToken()

    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit Profit</h4>
                <p class="card-description">
                    Edit the profit's information by filling the form below.
                </p>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.p_id)
                @Html.HiddenFor(model => model.p_investor)

                <form class="forms-sample">

                    <div class="form-group row">
                        @Html.LabelFor(model => model.p_month, "Year-Month", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.p_month, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                            @Html.ValidationMessageFor(model => model.p_month, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.p_investor, "Investor Name", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            <input class="form-control" value="@ViewBag.u_username" readonly disabled/>
                            @Html.ValidationMessageFor(model => model.p_investor, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.p_profit, "Profit (RM)", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.p_profit, new { htmlAttributes = new { @class = "form-control", @required = true } })
                            @Html.ValidationMessageFor(model => model.p_profit, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary mr-2" id="deleteButton">Save</button>
                    <button type="reset" class="btn btn-secondary mr-2">Reset</button>
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-light" })
                    <div id="confirmDeleteModal" style="display: none;">
                        <p>Are you sure you want to delete this transaction?</p>
                    </div>
                </form>

            </div>
        </div>
    </div>


}

XyTech/Views/Profit/Index.cshtml
@model IEnumerable<XyTech.Models.tb_profit>

@{
    ViewBag.Title = "Index";
}

<style>

    .dt-buttons {
        margin-bottom: 10px;
    }

        .dt-buttons button:hover {
            opacity: 0.8;
        }

        .dt-buttons button {
            margin-left: 5px;
            padding: 6px 12px;
            border: none;
            border-radius: 4px;
            font-size: 14px;
            cursor: pointer;
        }

        .dt-buttons .buttons-csv {
            background-color: cornflowerblue;
            color: white;
        }

        .dt-buttons .buttons-excel {
            background-color: seagreen;
            color: white;
        }

        .dt-buttons .buttons-pdf {
            background-color: red;
            color: white;
        }

        .dt-buttons .buttons-print {
            background-color: #607d8b;
            color: white;
        }
</style>

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @if (ViewBag.Message == "Profit is successfully edited!")
                {
                    <div class="alert alert-success">
                        <strong>@ViewBag.Message</strong>
                        <button type="button" class="close" data-dismiss="alert">
                            <span class="mdi mdi-close"></span>
                        </button>
                    </div>
                }

                <div class="d-flex justify-content-between">
                    <p class="card-title mb-0" style="font-size: x-large;">Investor Profit Sharing</p>

                </div>
                <br />
                @{
                    var sortedProfit = Model.OrderByDescending(p => int.Parse(p.p_month.Substring(0, 4))).ThenByDescending(p => int.Parse(p.p_month.Substring(5)));
                }

                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="display expandable-table" style="width:100%">
                                <thead>
                                    <tr>

                                        <th>
                                            Year
                                        </th>
                                        <th>
                                            Month
                                        </th>
                                        @if (Session["id"] != null && Session["usertype"].Equals("Admin"))
                                        {
                                            <th>
                                                Lot ID
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.InvestorUsername)
                                            </th>
                                        }
                                        <th>
                                            Profit Earned (RM)
                                        </th>
                                        @if (Session["id"] != null && Session["usertype"].Equals("Admin"))
                                        {
                                            <th>

                                            </th>
                                        }
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in sortedProfit)
                                    {
                                        var year = int.Parse(item.p_month.Substring(0, 4));
                                        var month = int.Parse(item.p_month.Substring(5));
                                        var currentDate = DateTime.Now;
                                        var isCurrentMonth = year == currentDate.Year && month == currentDate.Month;

                                        <tr>

                                            <td>
                                                @year
                                            </td>
                                            <td>
                                                @month
                                            </td>
                                            @if (Session["id"] != null && Session["usertype"].Equals("Admin"))
                                            {
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.p_lot)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.InvestorUsername)
                                                </td>
                                            }
                                            <td id="profit">
                                                @Html.DisplayFor(modelItem => item.p_profit)
                                            </td>
                                            @if (Session["id"] != null && Session["usertype"].Equals("Admin"))
                                            {
                                                <td>
                                                    @if (!isCurrentMonth)
                                                    {
                                                        <a href="@Url.Action("Edit", new { id = item.p_id })" class="btn btn-link" title="edit">
                                                            <i class="fa fa-edit text-primary"></i>
                                                        </a>
                                                    }

                                                </td>
                                            }
                                        </tr>
                                    }
                                </tbody>
                            </table>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            var currentDate = new Date().toISOString().slice(0, 10); // Get the current date in YYYY-MM-DD format

            $('#dataTable').DataTable({
                dom: '<"row"<"col-sm-3"l><"col-sm-6"f><"col-sm-3"B>>tip',
                buttons: [
                    {
                        extend: 'csv',
                        text: 'CSV',
                        filename: 'AR_InvestorProfit_' + currentDate,
                        footer: true

                    },
                    {
                        extend: 'excel',
                        text: 'Excel',
                        filename: 'AR_InvestorProfit_' + currentDate,
                        footer: true
                    },
                    {
                        extend: 'pdf',
                        text: 'PDF',
                        filename: 'AR_InvestorProfit_' + currentDate,
                        footer: true
                    },
                    {
                        extend: 'print',
                        text: 'Print',
                        footer: true
                    }
                ]
            });
        });

        var inflowAmounts = document.querySelectorAll("#profit");
        inflowAmounts.forEach(function (element) {
            element.textContent = parseFloat(element.textContent).toFixed(2);
        });

        document.addEventListener("DOMContentLoaded", function () {
            var allOption = document.querySelector('#f_floor option[value="select"]');
            allOption.disabled = true;
        });
    </script>
}