XyTech/Controllers/InvestorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using XyTech.Attributes;
using XyTech.Models;

namespace XyTech.Controllers
{
    [CustomAuthorize]
    public class InvestorController : Controller
    {
        private db_XyTechEntities db = new db_XyTechEntities();

        // GET: Investor
        public ActionResult Index()
        {
            ViewBag.countlandlord = db.tb_landlord.Count(l => l.l_due <= DateTime.Today && l.l_active == "1");
            int currentDay = DateTime.Today.Day;
            var tenants = db.tb_tenant.ToList();

            if (currentDay < 7 && tenants.Any(t => t.t_indate.Day > 23))
            {
                currentDay += 30;
            }
            ViewBag.counttenant = tenants.Count(t => t.t_indate.Day >= (currentDay - 7) && t.t_indate.Month != DateTime.Today.Month && t.t_indate.Day < currentDay && (t.t_paymentstatus == 2 || t.t_paymentstatus == 3));

            var tb_investor = db.tb_investor.Include(t => t.tb_user);
            if (TempData.Count > 0)
            {
                ViewBag.Message = TempData["success"].ToString();
            }
            return View(tb_investor.ToList());
        }

        // GET: Investor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_investor tb_investor = db.tb_investor.Find(id);
            if (tb_investor == null)
            {
                return HttpNotFound();
            }
            return View(tb_investor);
        }

        // GET: Investor/Create
        public ActionResult Create()
        {
            ViewBag.Username = TempData["InvestorUsername"] as string;

            using (var context = new XyTech.Models.db_XyTechEntities())
            {
                var username = ViewBag.Username as string;
                var user = context.tb_user.FirstOrDefault(u => u.u_username == username);
                if (user != null)
                {
                    var userList = context.tb_user.Select(u => new { u.u_id, u.u_username }).ToList();
                    ViewBag.i_user = new SelectList(userList, "u_id", "u_username", user.u_id);
                }
            }

            return View();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "i_id,i_user,i_lot,i_amount,i_active")] tb_investor tb_investor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = db.tb_user.Find(tb_investor.i_user);
                    var u_email = user.u_email;
                    var u_name = user.u_username;
                    var u_pwd = user.u_pwd;
                    email(u_email, u_name, u_pwd);

                    var userId = Convert.ToInt32(Session["id"]);
                    var financeTransaction = new tb_finance
                    {
                        f_floor = null, // Modify as per your requirement
                        f_date = DateTime.Now, // Set the finance transaction date to current date
                        f_transaction = tb_investor.i_amount, // Set the transaction amount as per your requirement
                        f_transactiontype = "Inflow", // Set the transaction type as per your requirement
                        f_paymentmethod = "Bank",
                        f_user = userId,
                        f_desc = "Investor " + u_name
                    };

                    //Hash Password

                    db.tb_finance.Add(financeTransaction);
                    db.tb_investor.Add(tb_investor);
                    TempData["success"] = "Investor is successfully saved!";
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    var errorMessages = ex.EntityValidationErrors
                        .SelectMany(e => e.ValidationErrors)
                        .Select(e => e.ErrorMessage);

                    // Log or handle the validation errors as needed
                    foreach (var errorMessage in errorMessages)
                    {
                        ModelState.AddModelError("", errorMessage);
                    }
                }
            }

            ViewBag.Username = TempData["InvestorUsername"] as string;
            using (var context = new XyTech.Models.db_XyTechEntities())
            {
                var username = ViewBag.Username as string;
                var user = context.tb_user.FirstOrDefault(u => u.u_username == username);
                if (user != null)
                {
                    var userList = context.tb_user.Select(u => new { u.u_id, u.u_username }).ToList();
                    ViewBag.i_user = new SelectList(userList, "u_id", "u_username", user.u_id);
                }
            }

            return View(tb_investor);
        }






        // GET: Investor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_investor tb_investor = db.tb_investor.Find(id);
            if (tb_investor == null)
            {
                return HttpNotFound();
            }
            ViewBag.i_user = new SelectList(db.tb_user, "u_id", "u_username", tb_investor.i_user);
            return View(tb_investor);
        }

        // POST: Investor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "i_id,i_user,i_lot,i_amount,i_active")] tb_investor tb_investor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_investor).State = EntityState.Modified;
                db.SaveChanges();
                TempData["success"] = "Investor is successfully saved!";
                return RedirectToAction("Index");
            }
            ViewBag.i_user = new SelectList(db.tb_user, "u_id", "u_username", tb_investor.i_user);
            return View(tb_investor);
        }

        // GET: Investor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            tb_investor tb_investor = db.tb_investor.Find(id);
            if (tb_investor == null)
            {
                return HttpNotFound();
            }
            bool existsInProfitTable = db.tb_profit.Any(p => p.p_investor == id);

            if (existsInProfitTable)
            {
                TempData["success"] = "Investor is associated with profit records and cannot be deleted.";
                return RedirectToAction("Index");
            }
            return View(tb_investor);
        }

        // POST: Investor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_investor tb_investor = db.tb_investor.Find(id);
            db.tb_investor.Remove(tb_investor);
            db.SaveChanges();
            TempData["success"] = "Investor is deleted.";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public void email(string u_email, string username, string password)
        {
            using (db_XyTechEntities dc = new db_XyTechEntities())
            {

                    var verifyUrl = "/Login";
                    var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

                    var fromEmail = new MailAddress("akmalrentalsjb@gmail.com", "Akmal Rentals");
                    var toEmail = new MailAddress(u_email);
                    var fromEmailPassword = "wiuiwiwnutfzbqrm";

                    string subject = "Akmal Rentals User Account";
                    string body = "Dear " + username +
                        ",<br/><br/>Your account has been created successfully. Here are your login credentials:<br/><br/>" +
                        $"Username: {username}<br/>Password: {password}" +
                        $"<br/><br/>Please keep these credentials secure and do not share them with anyone.<br/><br/>" +
                        $"You can log in to your account by clicking on the following link: " +
                        $"<a href='{link}'>Log In</a><br/><br/>Thank you for joining Akmal Rentals.";


                    using (MailMessage mail = new MailMessage())
                    {
                        mail.From = fromEmail;
                        mail.To.Add(toEmail);
                        mail.Subject = subject;
                        mail.Body = body;
                        mail.IsBodyHtml = true;
                        //mail.Attachments.Add(new Attachment("C:\\file.zip"));

                        using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                        {
                            smtp.UseDefaultCredentials = false;

XyTech/Views/Investor/ChooseUser.cshtml
@{
    ViewBag.Title = "ChooseUser";
}

<h2>ChooseUser</h2>

XyTech/Views/Investor/Create.cshtml
@model XyTech.Models.tb_investor

@{
    ViewBag.Title = "Create";
    var username = TempData["InvestorUsername"] as string;
    int userId = 0; // Initialize the user ID variable
    if (!string.IsNullOrEmpty(username))
    {
        ViewBag.Username = username;
        using (var context = new XyTech.Models.db_XyTechEntities())
        {
            var user = context.tb_user.FirstOrDefault(u => u.u_username == username);
            if (user != null)
            {
                userId = user.u_id;
            }
        }
    }
}


<div id="createInvestorModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Create New Investor</h2>
            </div>
            @using (Html.BeginForm("Create", "Investor", FormMethod.Post))
            {
                <div class="modal-body">

                    @Html.AntiForgeryToken()

                    <table class="table table-striped table-borderless">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <tr>
                            <td>@Html.LabelFor(model => model.i_user, "User ID")</td>
                            <td>@Html.TextBoxFor(model => model.i_user, new { @class = "form-control", @readonly = "readonly", Value = userId })</td>
                            <td>@Html.ValidationMessageFor(model => model.i_user, "", new { @class = "text-danger" })</td>
                        </tr>

                        <tr>
                            <td>@Html.LabelFor(model => model.tb_user.u_username, "Username")</td>
                            <td>@Html.TextBoxFor(model => model.tb_user.u_username, new { @class = "form-control", @readonly = "readonly", Value = ViewBag.Username })</td>
                            <td>@Html.ValidationMessageFor(model => model.tb_user.u_username, "", new { @class = "text-danger" })</td>
                        </tr>

                        <tr>
                            <td>@Html.LabelFor(model => model.i_lot, "Lot ID")</td>
                            <td>@Html.EditorFor(model => model.i_lot, new { htmlAttributes = new { @class = "form-control", required = true, type = "number", step = "1" } })</td>
                            @*<td>@Html.ValidationMessageFor(model => model.i_lot, "", new { @class = "text-danger" })</td>*@
                        </tr>

                        <tr>
                            <td>@Html.LabelFor(model => model.i_amount, "Amount")</td>
                            <td>@Html.TextBoxFor(model => model.i_amount, new { @class = "form-control", required = true, type = "number", min = "10000", max = "50000" })</td>
                            @*<td>@Html.ValidationMessageFor(model => model.i_amount, "", new { @class = "text-danger" })</td>*@
                        </tr>

                            @Html.DropDownList("i_active", new List<SelectListItem>
                            {
                                new SelectListItem { Text = "active", Value = "active", Selected = true},
                                new SelectListItem { Text = "inactive", Value = "inactive" }
                            }, new { @class = "form-control", @hidden = true })
                            @Html.HiddenFor(model => model.i_active, new { @value = "active" })
                    </table>


                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary mr-2">Create</button>
                </div>
            }
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#createInvestorModal').modal({ backdrop: 'static', keyboard: false });

        $('#tb_user_u_username').val('@ViewBag.Username');
    });
</script>

@*@using (Html.BeginForm("Create", "Investor", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.i_user, "User ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.i_user, new { @class = "form-control", @readonly = "readonly", Value = userId })
                @Html.ValidationMessageFor(model => model.i_user, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tb_user.u_username, "Username", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.tb_user.u_username, new { @class = "form-control", @readonly = "readonly", Value = ViewBag.Username })
                @Html.ValidationMessageFor(model => model.tb_user.u_username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.i_lot, "Lot ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.i_lot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.i_lot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.i_amount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.i_amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.i_amount, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.DropDownList("i_active", new List<SelectListItem>
            {
                new SelectListItem { Text = "active", Value = "active", Selected = true},
                new SelectListItem { Text = "inactive", Value = "inactive" }
            }, new { @class = "form-control", @hidden = true })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(model => model.i_active, new { @value = "active" })
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <script>
        $(document).ready(function () {
            $('#tb_user_u_username').val('@ViewBag.Username');
        });
    </script>
    @Html.ActionLink("Back to List", "Index")
</div>*@

XyTech/Views/Investor/Delete.cshtml
@model XyTech.Models.tb_investor

@{
    ViewBag.Title = "Delete";
}

<div align="center">
    <div align="left" class="col-lg-9 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Delete Investor</h4>
                <p class="card-description">
                    Are you sure you want to delete this investor?
                </p>
                <!--<hr />-->
                <div class="table-responsive">
                    <table class="table table-striped table-borderless">
                        <tbody>
                            <tr>
                                <th class="col-3">
                                    Username
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.tb_user.u_username)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Investor ID
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_id)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Lot ID
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_lot)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Amount (RM)
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_amount)
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color" style="margin-top: 25px;">
                        <input type="submit" value="Delete" class="btn btn-danger mr-2" onclick="return confirm('Are you sure to delete this investor?');" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-light" })
                    </div>
                }

            </div>
        </div>
    </div>
</div>

XyTech/Views/Investor/Details.cshtml
@model XyTech.Models.tb_investor

@{
    ViewBag.Title = "Details";
}

<div align="center">
    <div align="left" class="col-lg-9 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Investor</h4>
                <p class="card-description">
                    Details of investor
                </p>
                <!--<hr />-->
                <div class="table-responsive">
                    <table class="table table-striped table-borderless">
                        <tbody>
                            <tr>
                                <th class="col-3">
                                    Username
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.tb_user.u_username)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Investor ID
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_id)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Lot ID
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_lot)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Amount (RM)
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_amount)
                                </td>
                            </tr>

                            <tr>
                                <th class="col-3">
                                    Status
                                </th>

                                <td class="col-6">
                                    @Html.DisplayFor(model => model.i_active)
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>
                <div style="margin-top: 25px;">
                    @Html.ActionLink("Edit", "Edit", new { id = Model.i_id }, new { @class = "btn btn-primary mr-2" })
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-light" })

                </div>
            </div>
        </div>
    </div>
</div>

XyTech/Views/Investor/Edit.cshtml
@model XyTech.Models.tb_investor

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit Investor</h4>
                <p class="card-description">
                    Edit investor's information by filling the form below.
                </p>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.i_id)

                <form class="forms-sample">
                    <div class="form-group row">
                        @Html.LabelFor(model => model.i_user, "Username", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.DropDownList("i_user", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.i_user, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.i_lot, "Lot ID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.i_lot, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.i_lot, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.i_amount, "Amount (RM)", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.i_amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.i_amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.i_active, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.i_active, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.i_active, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-offset-2 col-sm-9">
                            <input type="submit" value="Save" class="btn btn-primary mr-2" />
                            <span>
                                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-light" })
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}